# Generated by Django 6.0.6 on 2026-07-07 01:08

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('original_url', models.URLField()),
                ('code', models.CharField()),
            ],
            options={
                'db_table': 'short_urls',
                'abstract': False,
                'indexes': [models.Index(fields=['code'], name='short_urls_code_65a119_idx')],
            },
            managers=[
                ('audit', django.db.models.manager.Manager()),
            ],
        ),
    ]
