# Generated by Django 6.0.6 on 2026-07-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shorturl',
            name='short_urls_code_65a119_idx',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='code',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['name'], name='short_urls_name_8d9086_idx'),
        ),
    ]
