# Generated by Django 6.0.6 on 2026-07-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_remove_shorturl_short_urls_code_65a119_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
