# Generated by Django 6.0.6 on 2026-07-25 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0003_alter_shorturl_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shorturl',
            name='short_urls_name_8d9086_idx',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['name', 'user'], name='short_urls_name_fa631a_idx'),
        ),
    ]
